# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
    
CiscoSystemsAuditBundle:
    resource: "@CiscoSystemsAuditBundle/Resources/config/routing.yml"
    prefix:   /cisco_audit
